spring:
  profiles:
    active: dev
  
---
spring:
  profiles: dev #开发时环境
  application:
    name: microservicecloud-config-dev


---
spring:
  profiles: tets #测试环境
  application:
    name: microservicecloud-config-test