# EurekaServer：通过Configser获取到git中对应EurekaServer的配置文件信息

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
server:
  port: 7004
eureka:
  instance:
    hostname: eureka7004.com
  client:
    register-with-eureka: false
    fetch-registry: false
    # service-url:
      # defaultZone: localhost:7004/eureka

---
spring:
  profiles: test
server:
  port: 7004
eureka:
  instance:
    hostname: eureka7004.com
  client:
    register-with-eureka: false
    fetch-registry: false
    # service-url:
      # defaultZone: localhost:7004/eureka
  