# EurekaServer：通过Configser获取到git中对应EurekaServer的配置文件信息

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
server:
  port: 7004
eureka:
  instance:
    instance-id: eureka7004.com:7004-dev
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: localhost:7004/eureka

---
spring:
  profiles: test
server:
  port: 7004
eureka:
  instance:
    instance-id: eureka7004.com:7004-test
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: localhost:7004/eureka
  